# Generated by Django 4.0.4 on 2022-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
