# Generated by Django 4.0.4 on 2022-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_accountnoticerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnoticerelation',
            name='is_in_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountnoticerelation',
            name='is_in_hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
