# Generated by Django 4.0.4 on 2022-05-12 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0005_remove_account_relation'),
        ('board', '0005_alter_accountnoticerelation_is_in_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='relation',
            field=models.ManyToManyField(related_name='relation', through='board.AccountNoticeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
