# Generated by Django 4.0.4 on 2022-05-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_account_address_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.address'),
        ),
    ]
