# Generated by Django 4.0.4 on 2022-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_accountnoticerelation'),
        ('user_auth', '0003_alter_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='relation',
            field=models.ManyToManyField(through='board.AccountNoticeRelation', to='board.notice'),
        ),
    ]
